name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Berjalan otomatis setiap 24 jam
  workflow_dispatch:   # Memungkinkan tombol manual "Run workflow"
  push:
    branches:
    - main
    - master           # Mendukung branch main maupun master

jobs:
  generate:
    permissions: 
      contents: write  # Memberikan izin menulis langsung dari dalam file
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate GitHub Animation Snake
        uses: Platane/snk@v3
        with:
          github_user_name: IvanderTheo
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9&color_background=#aaaaaa

      - name: Deploy to Output Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: output # Menyimpan semua hasil ke branch bernama output